export const ALERT_MESSAGE = {
  ID_LENGTH: '아이디는 15자 이하여야 합니다.',
  PASSWORD_LENGTH: '비밀번호는 15자 이하여야 합니다.',
  REQUEST_SUCCESS: '요청이 성공적으로 처리되었습니다.',
  REQUEST_ERROR: '요청 처리 중 에러가 발생했습니다.',
  LOGIN_ERROR: '로그인 정보가 일치하지 않습니다.',
  SAVE_SUCCESS: '성공적으로 저장되었습니다.',
  SAVE_ERROR: '저장에 실패했습니다.',
  NO_CHANGES: '변경사항이 없습니다.',
  NONE_EMPTY: '필수 입력 항목입니다.',
  ONLY_NUMBER: '숫자만 입력 가능합니다.',
  ONLY_NUMBER_AND_DASH: '숫자와 하이픈(-)만 입력 가능합니다.',
  ONLY_ENGLISH: '영문만 입력 가능합니다.',
  TELEPHONE: '올바른 전화번호 형식을 입력해 주세요.',
  EMAIL: '올바른 이메일 주소 형식을 입력해 주세요.',
  FILE: '파일을 선택해 주세요',
  FILE_FORMAT: '지원하지 않는 파일 형식입니다.',
  FILE_SIZE: '최대 파일 크기를 초과했습니다.',
  ORDER_CHANGE_FIRST: '더 이상 위로 이동할 수 없습니다.',
  ORDER_CHANGE_LAST: '더 이상 아래로 이동할 수 없습니다.',
  CANCEL: '작업을 취소하시겠습니까?',
  CANCEL_DESCRIPTION: '작업을 취소하면 작성된 내용이 사라집니다.',
}
